config/routes.rb
HackNight::Application.routes.draw do

  resources :hacknights

  resources :badges

  resources :projects

  resources :sponsors

  resources :hackers

  root :to => "index#index", :as => "index"
  match 'about' => "index#about"

  match 'hackers' => "hackers#index"
  match 'hackers/:id/update/hacknights' => "hackers#check_hacknights", :as => "update_hacknights"
  match 'projects/add_hacker' => "projects#add_hacker", :as => "add_hacker"
  match 'imgur' => "imgur#upload", :as => "imgur_api"
  match 'fb_add_hacker' => "hackers#create"

end

app/models/badge.rb
class Badge < ActiveRecord::Base
  validates :name, :image, :description, :presence => true
end

app/models/hacker.rb
class Hacker < ActiveRecord::Base
  validates :name, :email, :presence => true

  has_and_belongs_to_many :badges
  has_many :projects
  has_many :skills
end

app/models/hacknight.rb
class Hacknight < ActiveRecord::Base
  #Validate the event_id
  validates :venue, :event_id, :presence => true

  has_many :projects
  has_many :sponsors
  has_many :hackers
end

app/models/project.rb
class Project < ActiveRecord::Base
  validates :image_url, :name, :description, :presence => true
  validates_format_of :image_url, :with => /^(http|https):\/\/[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(([0-9]{1,5})?\/.*)?$/ix
  

  def validate_url
    if :image_url.match(/\.(jpg|png|gif)/)
      return true
    else
      return false
    end
  end

  has_many :hackers
  has_and_belongs_to_many :badges
  belongs_to :hacknight
end

app/models/skill.rb
class Skill < ActiveRecord::Base
  validates :name, :value, :presence=>true
  belongs_to :hacker
end

app/models/sponsor.rb
class Sponsor < ActiveRecord::Base
  validates :name, :description, :company_url, :logo_url, :presence => true

  has_and_belongs_to_many :hacknights
end

app/controllers/application_controller.rb
include Koala::Facebook
class ApplicationController < ActionController::Base
  protect_from_forgery


  @@imgur_api_key = "ba2b49a329da8a5310829c0adf78585d"

  # Retrieve the current user, set the user if not already
  def current_hacker
    @current_hacker ||= Hacker.find_by_id(session[:user_id])
  end


  # Helper method to assign and set user in session
  def current_hacker=(hacker)
      @current_hacker = hacker
      session[:user_id] = hacker.id
  end

  helper_method :current_hacker

end

app/controllers/badges_controller.rb
class BadgesController < ApplicationController
end

app/controllers/hackers_controller.rb
class HackersController < ApplicationController
  def index
    @hackers = Hacker.all
    current_hacker
  end

  def show
  end

  def edit
  end


  # This receives a post request and adds the hacker to our database if we don't have is email
  # (Email is unique)
  def create
    hackers = Hacker.where( :email => params[:email] )
    if hackers.empty?
      @hacker = Hacker.new({
        name=> params[:name],
        email=> params[:email],
        access_token=> params[:access_token],
        image_url=> params[:image_url],
        fb_id=> params[:fb_id]
      })
      if @hacker.save
        session[:user_id] = @hacker.id
        current_hacker = @hacker
        #render :text =>  "Added Hacker: " + @hacker.id.to_s + " Session: " + session[:user_id].to_s
      else
        render :text => @hacker.errors.full_messages
      end
    else
        session[:user_id] = hackers[0].id
        current_hacker = hackers[0]
        current_hacker.access_token = params[:access_token]
        current_hacker.save
        redirect_to index_path
        #render :text => session[:user_id].to_s
        #session[:user_id] = hackers[0].id
#        render :text =>  "Already have the hacker, Session: " + session[:user_id].to_s
    end
  end

  def check_hacknights
   @hacker = Hacker.find(params[:id])
   graph = Koala::Facebook::GraphAPI.new(@hacker.access_token)
   str = ""
   Hacknight.all.each do |night|
     attendees = graph.get_connections(night.event_id, "attending")
     attendees.each do |attendee|
       if @hacker.fb_id == attendee['id']
        night.hackers << @hacker
        render :text => "You attended Hack Night " + night.event_id
       end
     end
   end
#    render :text => #    render :text => session[:user_id]#current_hacker
    return
  end
end

app/controllers/hacknights_controller.rb
class HacknightsController < ApplicationController
  def new
    @hacknight = Hacknight.new
  end

  def index
    @hacknights = Hacknight.all
  end

  def create
    @hacknight = Hacknight.new(params[:hacknight])
    if @hacknight.save
        redirect_to(@hacknight, :notice => 'Hacknight was created successfully')
    else
        flash[:errors] = @hacknight.errors.full_messages
        render :action => "new"
    end
  end

  def edit
    @hacknight = Hacknight.find(params[:id])
  end

  def show
    @hacknight = Hacknight.find(params[:id])
    @projects = @hacknight.projects
    @sponsors = @hacknight.sponsors
  end

  def add_hacker
    @hacknight = Hacknight.find(params[:hacknight][:id])
    if params[:hacker]
      @hacker = Hacker.find(params[:hacker][:id]) 
      @hacknight.hackers << @hacker
    end

    if @hacknight.save
      redirect_to(@hacknight, :notice => "Hacker was added!")
    else
      flash[:errors] = @hacknight.errors.full_messages
    end
  end

  def update
    @hacknight = Hacknight.find(params[:id])
    if(@hacknight.update_attributes(params[:hacknight]))
      redirect_to(@hacknight)
    else
      redirect_to(edit_hacknight_path(@hacknight))
    end
  end

  def destroy
    Hacknight.find(params[:id]).destroy
    redirect_to :action => 'index'
  end

end

app/controllers/imgur_controller.rb
class ImgurController < ApplicationController

def upload
#  render :text => 'Hello World'
   filename = params[:project][:filename]
   filedata = filename.read
   render :text => filedata
end

end

app/controllers/index_controller.rb
class IndexController < ApplicationController

layout 'application'

def index
  @sponsors = Sponsor.all
end

def about
  render :about
end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  def new
    @project = Project.new
  end

  def index
    @projects = Project.all
  end

  def create
    @project = Project.new(params[:project])
    if @project.save
        redirect_to(@project, :notice => 'Project was created successfully')
    else
        flash[:errors] = @project.errors.full_messages
        render :action => "new"
    end
  end

  def edit
    @project = Project.find(params[:id])
  end

  def show
    @project = Project.find(params[:id])
    @hackers = Hacker.all
  end

  def add_hacker
    @project = Project.find(params[:project][:id])
    if params[:hacker]
      @hacker = Hacker.find(params[:hacker][:id]) 
      @project.hackers << @hacker
    end

    if @project.save
      redirect_to(@project, :notice => "Hacker was added!")
    else
      flash[:errors] = @project.errors.full_messages
    end
  end

  def update
    @project = Project.find(params[:id])
    if(@project.update_attributes(params[:project]))
      redirect_to(@project)
    else
      redirect_to(edit_project_path(@project))
    end
  end

  def destroy
    Project.find(params[:id]).destroy
    redirect_to :action => 'index'
  end
end

app/controllers/sponsors_controller.rb
class SponsorsController < ApplicationController

  def new
    @sponsor = Sponsor.new
  end

  def index
    @sponsors = Sponsor.all
  end

  def create
    @sponsor = Sponsor.new(params[:sponsor])
    if @sponsor.save
      redirect_to(@sponsor) 
      #redirect_to :action => 'show', :id => @sponsor.id
    else
      flash[:errors] = @sponsor.errors.full_messages
      render :action => "new"
    end
  end

  def edit
    @sponsor = Sponsor.find(params[:id])
  end

  def show
    @sponsor = Sponsor.find(params[:id])
    @hacknights = Hacknight.all
  end

  def update
    @sponsor = Sponsor.find(params[:id])
    if(@sponsor.update_attributes(params[:sponsor]))
      redirect_to(@sponsor)
    else
      redirect_to(edit_sponsor_path(@sponsor))
    end
  end

  def destroy
    Sponsor.find(params[:id]).destroy
    redirect_to :action => 'index'
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/badges_helper.rb
module BadgesHelper
end

app/helpers/hackers_helper.rb
module HackersHelper
end

app/helpers/hacknights_helper.rb
module HacknightsHelper
end

app/helpers/imgur_helper.rb
module ImgurHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/sponsors_helper.rb
module SponsorsHelper
end

app/views/hackers/index.html.erb
<div id="title-header">
  <h2>The <span class="accent">Hackers</span></h2>
</div>
<div id="content">
  <% if current_hacker %>
    <%= link_to("Update Hacknights", update_hacknights_path(current_hacker.id), :id=>"button") %>
  <% end %>
  <% @hackers.each do |hacker| %>
    <img src="<%=hacker.image_url %>" />
  <% end %>
</div>

app/views/hacknights/_form.html.erb
<% content_for :head do %>
  <%= javascript_include_tag "jquery.form" %>
<% end %>

<%= form_for @hacknight, :html => {:id => "submit-form"} do |f| %>
  <% if flash[:errors] %>
    <ul id="errors">
    <% flash[:errors].each do |error|%>
      <li><%= error.to_s.humanize %><br /></li>
    <% end %>
    </ul>
  <% end %>
  <%= f.text_field :name, :placeholder => "Hack Night Name" %>
  <%= f.text_field :venue, :placeholder => "Hack Night Venue" %>
  <!--Need to validate event_id format-->
  <%= f.text_field :event_id, :placeholder => "Facebook Event Id" %>
  <%= submit_tag "Save Hack Night" %>
<% end %>
<%= javascript_include_tag "image_upload" %>

app/views/hacknights/edit.html.erb
<div id="title-header">
  <h2>Editing <span class="accent"><%= @hacknight.name %></span></h2>
</div>
<div id="content">
<%= render 'form' %>
</div>

app/views/hacknights/index.html.erb
<div id="title-header">
  <h2><span class="accent">Hack Nights<span></h2>
</div>
<div id="content">
  <%= link_to("Add a Hack Night", new_project_path, :id=>"button") %>
  <ul class="list">
  <% @hacknights.each do |hacknight| %>
    <li>
      <div class="name">
        <%= link_to(hacknight.name, hacknight) %>
      </div>
    </li>
  <% end %>
  </ul>
</div>

app/views/hacknights/new.html.erb
<div id="title-header">
  <h2>Create a <span class="accent">Hacknight</span></h2>
</div>
<div id="content">
<%= render 'form' %>
</div>

app/views/hacknights/show.html.erb
<div id="title-header">
  <!--TODO:Change this title-->
  <h2>a Hacknight</h2>
</div>
<div id="content">
  <div id="card">
    <ul id="info">
      <li><span class="accent">Venue:</span> <%= @hacknight.venue%></li>
      <li><span class="accent">EID:</span> <%= @hacknight.event_id%></li>
      <li><%= link_to("Edit", edit_hacknight_path(@hacknight.id)) %></li>
    </ul>
  </div>
</div>
<div id="title-header">
  <h2><span class="accent">Achievements</span></h2>
</div>
<div id="title-header">
  <h2><span class="accent">Sponsored</span> By</h2>
</div>

app/views/projects/_form.html.erb
<% content_for :head do %>
  <%= javascript_include_tag "jquery.form" %>
<% end %>

<%= form_for @project, :html => {:id => "submit-form"} do |f| %>
  <% if flash[:errors] %>
    <ul id="errors">
    <% flash[:errors].each do |error|%>
      <li><%= error.to_s.humanize %><br /></li>
    <% end %>
    </ul>
  <% end %>
  <%= f.text_field :name, :placeholder => "Project Name" %>
  <%= f.text_field :image_url, :placeholder => "Image URL (use imgur.com for a host)" %>
  <%= f.text_field :project_url, :placeholder => "Project URL (optional)" %>
  <%= f.text_area :description, :placeholder => "Description" %>
  <%= submit_tag "Save Project" %>
<% end %>
<%= javascript_include_tag "image_upload" %>

app/views/projects/edit.html.erb
<div id="title-header">
  <h2>Editing <span class="accent"><%= @project.name %></span></h2>
</div>
<div id="content">
<%= render 'form' %>
</div>

app/views/projects/index.html.erb
<div id="title-header">
  <h2>The <span class="accent">Projects<span></h2>
</div>
<div id="content">
  <%= link_to("Create a Project", new_project_path, :id=>"button") %>
  <ul id="projects-list">
  <% @projects.each do |project| %>
    <li>
      <div id="project-name">
        <%= link_to(project.name, project) %>
      </div>
      <img src="<%= project.image_url %>"/ height="100px">
      <div id="project-desc">
        <%= project.description %>
      </div>
    </li>
  <% end %>
  </ul>
</div>

app/views/projects/new.html.erb
<div id="title-header">
  <h2>Add a <span class="accent">Hack Night</span></h2>
</div>
<div id="content">
<%= render 'form' %>
</div>

app/views/projects/show.html.erb
<div id="title-header">
  <h2>Presenting <span class="accent"><%= @project.name %></span></h2>
</div>

<div id="content">
  <div id="card">
    <ul id="info">
      <li><span class="accent">Name:</span> <%= @project.name %></li>
      <li><span class="accent">Links:</span> <%= link_to("Project Website", @project.project_url) %></li>
      <span class="accent">Venue:</span> <%= @project.hacknight%>
      <li><%= link_to("Edit", edit_project_path(@project.id)) %></li>
    </ul>
    <img src="<%= @project.image_url %>" />
  </div>
</div>
<div id="title-header">
  <h2><span class="accent">Built</span> By</h2>
  <div id="content">
    <% @project.hackers.each do |hacker| %>
        <img src="<%= hacker.image_url %>" />
    <% end %>
    <%= form_tag( add_hacker_path, :method => "post" ) do%>
      <%= collection_select(:hacker, :id, @hackers, :id, :name) %>
      <%= hidden_field(:project, :id) %>
      <%= submit_tag("Add Hacker", :id=>"button") %>
    <% end %>
  </div>
</div>
<div id="title-header">
  <h2><span class="accent">Sponsored</span> By</h2>
  <div id="content">
  </div>
</div>

app/views/sponsors/_form.html.erb
<%= form_for(@sponsor) do |f| %>
  <% if flash[:errors] %>
    <ul id="errors">
    <% flash[:errors].each do |error|%>
      <li><%= error.to_s.humanize %><br /></li>
    <% end %>
    </ul>
  <% end %>
  <%= f.text_field :name, :placeholder => "Sponsor Name" %>
  <%= f.text_field :logo_url, :placeholder => "Logo Image URL" %>
  <%= f.text_field :company_url, :placeholder => "Sponsor URL" %>
  <%= f.text_area :description, :placeholder => "Sponsor Description" %>
  <%= submit_tag "Save Sponsor" %>
<% end %>

app/views/sponsors/edit.html.erb
<div id="title-header">
  <h2>Editing <span class="accent"><%= @sponsor.name %></span></h2>
</div>
<div id="content">
<%= render 'form' %>
</div>

app/views/sponsors/index.html.erb
<div id="title-header">
  <h2>The <span class="accent">Sponsors</span></h2>
</div>
<div id="content">
  <%= link_to("Become a Sponsor", new_sponsor_path, :id=>"button") %>
  <% @sponsors.each do |sponsor| %>
    <a href=<%= sponsor_path(sponsor)%>><%= image_tag(sponsor.logo_url, :height => "100", :class => "sponsor_logo") %></a>
  <%end%>
</div>

app/views/sponsors/new.html.erb
<div id="title-header">
  <h2>Add a <span class="accent">Sponsor</span></h2>
</div>
<div id="content">
<%= render :partial => 'form' %>
</div>

app/views/sponsors/show.html.erb
<div id="title-header">
  <h2>Thank you <span class="accent"><%= @sponsor.name %></span></h2>
</div>

<div id="content">
  <div id="card">
    <ul id="info">
      <li><span class="accent">Name:</span> <%= @sponsor.name %></li>
      <% if @sponsor.company_url? %>
        <span class="accent">URL:</span> <%= @sponsor.company_url %>
      <% end %>
      <li><span class="accent">Description: </span><%= @sponsor.description %></li>
      <li><%= link_to("Edit", edit_sponsor_path(@sponsor.id)) %></li>
    </ul>
    <img src="<%= @sponsor.logo_url %>" />
  </div>
</div>
<div id="title-header">
  <h2>Sponsored  <span class="accent">Hack Nights</span></h2>
  <div id="content">
    <% @hacknights.each do |hacknight| %>
        <%= hacknight.venue %>
    <% end %>
  </div>
</div>