config/routes.rb
HackNight::Application.routes.draw do

  resources :hacknights

  resources :badges

  resources :projects

  resources :sponsors

  resources :hackers

  root :to => "index#index", :as => "index"
  match 'about' => "index#about"

  match 'hackers' => "hackers#index"
  match 'hackers/:id/update/hacknights' => "hackers#check_hacknights", :as => "update_hacknights"
  match 'projects/add_hacker' => "projects#add_hacker", :as => "add_hacker"
  match 'imgur' => "imgur#upload", :as => "imgur_api"
  match 'fb_add_hacker' => "hackers#create"

end

app/models/badge.rb
class Badge < ActiveRecord::Base
  validates :name, :image, :description, :presence => true
end

app/models/hacker.rb
class Hacker < ActiveRecord::Base
  validates :name, :email, :presence => true

  has_and_belongs_to_many :badges
  has_many :projects
  has_many :skills
end

app/models/hacknight.rb
class Hacknight < ActiveRecord::Base
  #Validate the event_id
  validates :venue, :event_id, :presence => true

  has_many :projects
  has_many :sponsors
  has_many :hackers
end

app/models/project.rb
class Project < ActiveRecord::Base
  validates :image_url, :name, :description, :presence => true
  validates_format_of :image_url, :with => /^(http|https):\/\/[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(([0-9]{1,5})?\/.*)?$/ix
  

  def validate_url
    if :image_url.match(/\.(jpg|png|gif)/)
      return true
    else
      return false
    end
  end

  has_many :hackers
  has_and_belongs_to_many :badges
  belongs_to :hacknight
end

app/models/skill.rb
class Skill < ActiveRecord::Base
  validates :name, :value, :presence=>true
  belongs_to :hacker
end

app/models/sponsor.rb
class Sponsor < ActiveRecord::Base
  validates :name, :description, :company_url, :logo_url, :presence => true

  has_and_belongs_to_many :hacknights
end

app/controllers/badges_controller.rb
class BadgesController < ApplicationController
end

app/controllers/hackers_controller.rb
class HackersController < ApplicationController
  def index
    @hackers = Hacker.all
    current_hacker
  end

  def show
  end

  def edit
  end


  # This receives a post request and adds the hacker to our database if we don't have is email
  # (Email is unique)
  def create
    hackers = Hacker.where( :email => params[:email] )
    if hackers.empty?
      @hacker = Hacker.new({
        name=> params[:name],
        email=> params[:email],
        access_token=> params[:access_token],
        image_url=> params[:image_url],
        fb_id=> params[:fb_id]
      })
      if @hacker.save
        session[:user_id] = @hacker.id
        current_hacker = @hacker
        #render :text =>  "Added Hacker: " + @hacker.id.to_s + " Session: " + session[:user_id].to_s
      else
        render :text => @hacker.errors.full_messages
      end
    else
        session[:user_id] = hackers[0].id
        current_hacker = hackers[0]
        current_hacker.access_token = params[:access_token]
        current_hacker.save
        redirect_to index_path
        #render :text => session[:user_id].to_s
        #session[:user_id] = hackers[0].id
#        render :text =>  "Already have the hacker, Session: " + session[:user_id].to_s
    end
  end

  def check_hacknights
   @hacker = Hacker.find(params[:id])
   graph = Koala::Facebook::GraphAPI.new(@hacker.access_token)
   str = ""
   Hacknight.all.each do |night|
     attendees = graph.get_connections(night.event_id, "attending")
     attendees.each do |attendee|
       if @hacker.fb_id == attendee['id']
        night.hackers << @hacker
        render :text => "You attended Hack Night " + night.event_id
       end
     end
   end
#    render :text => #    render :text => session[:user_id]#current_hacker
    return
  end
end

app/controllers/imgur_controller.rb
class ImgurController < ApplicationController

def upload
#  render :text => 'Hello World'
   filename = params[:project][:filename]
   filedata = filename.read
   render :text => filedata
end

end

app/controllers/index_controller.rb
class IndexController < ApplicationController

layout 'application'

def index
  @sponsors = Sponsor.all
end

def about
  render :about
end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  def new
    @project = Project.new
  end

  def index
    @projects = Project.all
  end

  def create
    @project = Project.new(params[:project])
    if @project.save
        redirect_to(@project, :notice => 'Project was created successfully')
    else
        flash[:errors] = @project.errors.full_messages
        render :action => "new"
    end
  end

  def edit
    @project = Project.find(params[:id])
  end

  def show
    @project = Project.find(params[:id])
    @hackers = Hacker.all
  end

  def add_hacker
    @project = Project.find(params[:project][:id])
    if params[:hacker]
      @hacker = Hacker.find(params[:hacker][:id]) 
      @project.hackers << @hacker
    end

    if @project.save
      redirect_to(@project, :notice => "Hacker was added!")
    else
      flash[:errors] = @project.errors.full_messages
    end
  end

  def update
    @project = Project.find(params[:id])
    if(@project.update_attributes(params[:project]))
      redirect_to(@project)
    else
      redirect_to(edit_project_path(@project))
    end
  end

  def destroy
    Project.find(params[:id]).destroy
    redirect_to :action => 'index'
  end
end

app/controllers/sponsors_controller.rb
class SponsorsController < ApplicationController

  def new
    @sponsor = Sponsor.new
  end

  def index
    @sponsors = Sponsor.all
  end

  def create
    @sponsor = Sponsor.new(params[:sponsor])
    if @sponsor.save
      redirect_to(@sponsor) 
      #redirect_to :action => 'show', :id => @sponsor.id
    else
      flash[:errors] = @sponsor.errors.full_messages
      render :action => "new"
    end
  end

  def edit
    @sponsor = Sponsor.find(params[:id])
  end

  def show
    @sponsor = Sponsor.find(params[:id])
    @hacknights = Hacknight.all
  end

  def update
    @sponsor = Sponsor.find(params[:id])
    if(@sponsor.update_attributes(params[:sponsor]))
      redirect_to(@sponsor)
    else
      redirect_to(edit_sponsor_path(@sponsor))
    end
  end

  def destroy
    Sponsor.find(params[:id]).destroy
    redirect_to :action => 'index'
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/badges_helper.rb
module BadgesHelper
end

app/helpers/hackers_helper.rb
module HackersHelper
end

app/helpers/hacknights_helper.rb
module HacknightsHelper
end

app/helpers/imgur_helper.rb
module ImgurHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/sponsors_helper.rb
module SponsorsHelper
end

app/views/index/about.html.erb
<div id="title-header">
  <h2>Story of <span class="accent">HackNight</span></h2>
</div>

app/views/index/index.html.erb
<script>
		$(function(){
			$('#slides').slides({
				preload: true,
				generateNextPrev: false,
				play: 5000,
				pause: 2500,
				hoverPause: true,
                pagination: false,
                container: "slides_container",
                generatePagination: false,
				animationStart: function(current){
					$('.caption').animate({
						bottom:-35
					},100);
				},
				animationComplete: function(current){
					$('.caption').animate({
						bottom:4
					},200);
				},
				slidesLoaded: function() {
					$('.caption').animate({
						bottom:4
					},200);
				}
            
			});
		});
 </script>
<div id="slides">
  <div id="title-header">
    <a class="prev" href="#"></a>
    <a class="next" href="#"></a>
    <h2>Featured <span class="accent">Hackers</span></h2>
  </div>
		<div class="slides_container">
			<div>
            <img src="images/slideshow_images/IMG_1506.JPG"/>
            <div class="caption">
              <h1>Team White Guys</h1>
              <p>Developing a better hamburger. We're taking over the world</p>
           </div>
			</div>
			<div>
            <img src="images/slideshow_images/IMG_1507.JPG"/>
            <div class="caption">
              <h1>Red Bull Fueled</h1>
              <p>We want more Red Bull!</p>
            </div>
			</div>
			<div>
            <img src="images/slideshow_images/IMG_1510.JPG"/>
            <div class="caption">
              <h1>Awesome Sponsors</h1>
              <p>Thanks to our sponsors for help funding the next Myspace... er Facebook</p>
           </div>
			</div>
			<div>
            <img src="images/slideshow_images/IMG_1511.JPG"/>
            <div class="caption">
              <h1>Slacker Hacker</h1>
              <p>A wild slacker hacker has been spotted!</p>
            </div>
			</div>
		</div>
</div>
<div id="title-header">
  <h2>Sponsors <span class="accent">&</span> Friends</h2>

  <% @sponsors.each do |sponsor| %>
    <%= image_tag(sponsor.logo_url, :height => "100", :class => "sponsor_logo") %>
  <%end%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HackNight</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag "jquery.min.js", "fb.js", "slides.min.jquery.js" %>
  <%= csrf_meta_tag %>
  <%= yield :head %>
  <%= javascript_tag "var AUTH_TOKEN = #{form_authenticity_token.inspect};" if protect_against_forgery? %>
</head>
<body>

<div id="wrapper2">
  <div id="left_bg"></div>
  <div id="right_bg"></div>
  <div id="wrapper">
    <div id="header">
        <div id="fb-root"></div>
        
        <div id ="fb-profile">
          <h2></h2>
          <%if(@hacker_pic)%>
            <%= image_tag(@hacker_pic) %>
          <%end%>
        </div>
      <% if current_hacker %>
        <div id="fb-profile"><%= current_hacker.name %><img src="<%= current_hacker.image_url %>"/></div>
      <% else %>
        <fb:login-button id="fb-login" style="display: none;" perms="email, user_events, offline_access">Login with Facebook</fb:login-button>
      <% end %>
      <div id="logo">
        <%= image_tag('hack.png') %>
        <div id="text">
          <%= link_to("Hack", index_path) %><span class="subtext">Night</span>
        </div>
      </div>
      <ul id="nav">
        <li><%= link_to("Hackers", hackers_path) %></li>
        <li><%= link_to("Projects", projects_path) %></li>
        <li><%= link_to("Sponsors", sponsors_path) %></li>
        <li><a href="/about"> About </a></li> 
      </ul>
    </div>
      <%= yield %>
    <div id="footer"></div>
  </div>
</div>
  <script src="http://connect.facebook.net/en_US/all.js"></script>
</body>
</html>